### ISSUE TITLE
error with resource_path function call

### ISSUE THREAD

**Issue by amakkonen** [supermundano/sage-the-events-calendar#6]
Hi,

there's an error in src/TheEventsCalendar.php on line 39 that results in fatal error.

Changing resource_path() to \Roots\resource_path() fixed the error in my case.

**Comment by cfaria** [comment]
Good catch! Thank you @amakkonen 

I'll fix it asap.

**Comment by EHLOVader** [comment]
This is odd, it didn't cause errors on mine, perhaps it is a version of PHP issue where namespace resolution has become more strict.

Looking at `\Roots\resource_path()` it is @deprecated so I don't think that is the one that should be used. 

It is basically an alias for `\resource_path` so that should probably be used now.
